// Copyright Xiao Studio, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

#define LOCTEXT_NAMESPACE "LicenseAgreement"

const static FText LicenseAgreement = LOCTEXT("LicenseAgreement_Text", "                                                  XiaoBuild License Agreement\n"
	"PLEASE READ CAREFULLY THE THIS LICENSE AGREEMENT(\"AGREEMENT\") BEFORE"
	"ACCEPTING IT AND REGISTERING FOR, ACCESSING, DOWNLOADING OR USING THE"
	"XiaoBuild SOFTWARE PRODUCT IN OBJECT CODE FORM, (\"SOFTWARE PRODUCT\")"
	"AND THE XiaoBuild CLOUD SERVICES(\"CLOUD SERVICES\")."
	"\n"
	"BY SELECTING THE BOX \"I AGREE\", \"ACCEPT\" OR SIMILAR, OR OTHERWISE DOWNLOADING, "
	"ACCESSING OR USING THE SOFTWARE PRODUCT AND CLOUD SERVICES, YOU"
	"ACKNOWLEDGE THAT YOU, ON YOUR BEHALF AS AN INDIVIDUAL AND ON BEHALF OF YOUR"
	"EMPLOYER OR ANOTHER LEGAL ENTITY(COLLECTIVELY \"LICENSEE\"), HAVE READ,"
	"UNDERSTOOD AND AGREE TO COMPLY WITH, AND BE LEGALLY BOUND BY, THE TERMS AND"
	"CONDITIONS OF THIS AGREEMENT, AND ARE ENTERING INTO A BINDING LEGAL AGREEMENT"
	"WITH XiaoBuild SOFTWARE LTD. (\"XiaoBuild\").YOU REPRESENT AND WARRANT"
	"THAT YOU ARE AT LEAST EIGHTEEN(18) YEARS OLD AND, IF YOU ARE ENTERING INTO THIS"
	"AGREEMENT ON BEHALF OF YOUR EMPLOYER OR OTHER LEGAL ENTITY, THAT YOU HAVE"
	"FULL AUTHORITY TO BIND SAID EMPLOYER OR OTHER LEGAL ENTITY TO THIS AGREEMENT."
	"IF YOU DO NOT AGREE TO COMPLY WITH AND BE BOUND BY THIS AGREEMENT OR DO NOT"
	"HAVE AUTHORITY TO BIND YOUR EMPLOYER OR OTHER LEGAL ENTITY, PLEASE DO NOT"
	"ACCEPT THIS AGREEMENT AND DO NOT DOWNLOAD, INSTALL, ACCESS OR USE THE"
	"SOFTWARE PRODUCT AND CLOUD SERVICES.YOU HEREBY WAIVE ANY RIGHTS TO"
	"REQUIRE AN ORIGINAL(NON - ELECTRONIC) SIGNATURE OR DELIVERY OR RETENTION OF"
	"NON - ELECTRONIC RECORDS, TO THE EXTENT PERMITTED UNDER APPLICABLE LAW."
	"\n"
	"In the event of any conflict between this Agreement and any agreement entered into between you and a"
	"partner, reseller or distributor authorized by XiaoBuild(each a \"Partner\"), or an online marketplace"
	"which enables Licensee to connect to XiaoBuild Cloud Services via Licensee’s marketplace account"
	"(\"Marketplace\"), then, as between you and XiaoBuild, this Agreement shall prevail.Any rights granted"
	"to you in the terms and /or order form between you and a Partner or Marketplace(collectively, \"Partner"
	"	Order Form\"), which are not included in this Agreement, apply only in connection with such Partner or"
	"Marketplace(as applicable).In that case, you must seek redress, realization or enforcement of such"
	"rights solely with such Partner or Marketplace(as applicable) and not with XiaoBuild."
	"\n"
	"1. LICENSE"
	"\n"
	"The specific usage rights granted to Licensee are as set forth below, depending on the type of license"
	"Licensee has acquired under the applicable Quote or Partner Order Form(as the case may be).For"
	"the purpose of this Agreement \"Quote\" means, any written or electronic order form(i) issued by"
	"XiaoBuild and agreed to by Licensee by execution, or (ii)issued by Licensee pursuant to a proposal"
	"made by XiaoBuild to Licensee, provided that such order incorporates by reference this Agreement,"
	"such that any terms and conditions within such order which are in addition to and /or inconsistent with"
	"this Agreement, shall be of no effect."
	"\n"
	"1.1 Subscription License.Subject to Licensee’s compliance with the terms and conditions of this"
	"Agreement(including, but not limited to, payment obligations), XiaoBuild grants to Licensee, and"
	"Licensee accepts, a non - exclusive, non - sublicensable, worldwide, non - transferable limited license to"
	"use the Software Product and /or the Cloud Services, during the Subscription Term(all as defined"
	"	below), solely by Licensee and /or its personnel, for Licensee’s internal business purposes"
	"	(\"Subscription License\").Licensee acknowledges that the Subscription License is subject to additional"
	"use restrictions and /or limitations specified in the Quote or the Partner Order Form(as the case may"
	"	be), such as but not limited to, the maximum number of initiators and helper cores, and /or cloud hours,"
	"whether the license can be used with the Software Product, the Cloud Services or both, and any other"
	"software editions, modules or use restrictions as designated and defined in the Quote or the Partner"
	"Order Form which, for the avoidance of doubt, are in addition to, and without derogating from, any"
	"other use restrictions set forth herein.Use of the initiator of the Software is allowed only on a single"
	"developer machine."
	"\n"
	"An “initiator” means the XiaoBuild agent executing the workload; a “helper core” means the cores"
	"that participate in a build that was executed by the initiator; “cloud hours” means the helper cores up"
	"time on the cloud; a \"CI\" means any machine initiating a workload that is not a developer workstation."
	"\n"
	"An initiator license is a node - locked license(as described in the documentation available at"
	"	https ://docs.XiaoBuild.com), unless otherwise approved in advance and in writing by XiaoBuild, "
	"and cannot be used for CI machines.Per Licensee's request, XiaoBuild may issue a specific "
	"dedicated license for the purpose of using the Software Product and /or the Cloud Services for CI"
	"machines."
	"\n"
	"1.2 Evaluation License.Subject to Licensee’s compliance with the terms and conditions of this"
	"Agreement, XiaoBuild may, at its sole discretion, grant Licensee a non - exclusive, non - sublicensable,"
	"non - transferable limited license to use the Software Product, the Cloud Services or additional"
	"components or features provided by XiaoBuild(\"Feature\"), for Licensee’s internal trial use in order to"
	"evaluate whether to purchase a subscription license for the Software Product, the Cloud Services or a"
	"Feature(as the case may be).Such license shall be a free of charge, limited license to use the"
	"Software Product or the Cloud Services(as applicable) for a period of thirty(30) days, or the Feature"
	"for a trial period at XiaoBuild's discretion, or such other period prescribed by XiaoBuild or the "
	"Partner in writing, or otherwise specified within the Marketplace(unless terminated earlier by either"
	"party according to Section 12 below) (“Evaluation Period”).The evaluation license may be subject to"
	"additional limitations as shall be prescribed by XiaoBuild in writing.At any time during the Evaluation"
	"Period, or upon expiration of the Evaluation License, XiaoBuild and Licensee may agree  in writing"
	"by execution of an applicable Quote to enter into a Subscription License to use the Software Product"
	"the Cloud Service or the Feature(as the case may be), subject to payment of the applicable"
	"Subscription Fee, the terms of this Agreement and the terms set forth in the said Quote."
	"\n"
	"1.3 Free License.Subject to Licensee’s compliance with the terms and conditions of this Agreement,"
	"XiaoBuild may grant Licensee, at its sole discretion, a non - exclusive, non - sublicensable, non -"
	"transferable, limited license to use a free version of the Software Product or the Cloud Services, for"
	"Licensee’s internal business purposes(“Free License”).The Free License may be offered directly by"
	"XiaoBuild, or within the Marketplace, and shall be free of charge, limited to the terms of Section 2"
	"below, and additional terms  as may be prescribed by XiaoBuild, or specified within the Marketplace"
	"(such as the scope and duration of the license).The Free License to the Software Product is limited to"
	"use of one copy of the Software Product within a single computer of the Licensee;  the Free License to"
	"the Cloud Services is limited to the scope specified within the Marketplace.FreeFor clarity,"
	"XiaoBuild may at any time terminate the Free License upon notice to Licensee."
	"\n"
	"It is hereby acknowledged, that upon your use, download or installation of freethe Software Product, the"
	"Cloud Services or a Feature, under any of the Licenses described above, XiaoBuild may collect,"
	"gather and store analytics and telemetry data related to Licensee’s use thereof(“Telemetry Data”), and"
	"use such Telemetry Data without limitation of any kind during or after the expiration or termination of"
	"this Agreement(for clarity the rights to collect, gather and store the Telemetry Data shall survive the"
	"	expiration or termination of this Agreement for any reason).Licensee may, at any point, prevent"
	"XiaoBuild from further collecting new Telemetry Data by : (i) if using the Free License or the"
	"Evaluation License, uninstalling the Free version of the Software, or (ii) if using s Subscription License,"
	"opting - out in accordance with the XiaoBuild Privacy Policy, at amended from time to time, and"
	"available at : https://www.XiaoBuild.com/privacy-policy. "
	"\n"
	"2. PROHIBITED USE."
	"\n"
	"Other than the rights explicitly granted in this Agreement, Licensee shall have no other rights, express"
	"or implied, in the Software Product, Cloud Services and /or any Feature.Without limiting the generality"
	"of the foregoing, with respect to each of the Software Product, Cloud Services and Feature"
	"(collectively, including any part thereof, \"Products\"), Licensee agrees and undertakes not to, directly or"
	"indirectly:"
	"\n"
	"(i)sell, lease, sublicense or distribute the Products, or any part thereof, or otherwise transfer or allow"
	"any third party to use the Products in any manner; (ii)reverse engineer, decompile, disassemble or"
	"otherwise reduce to human - perceivable form the Products’ source code; (iii)modify, revise, enhance"
	"or alter the Products; (iv)copy or allow copies of the Products to be made except as provided under"
	"this Agreement; (v)use any backup or archival copies of the Products or any part thereof, or allow any"
	"third party to use such copies, for any purpose other than to replace an original copy in the event of the"
	"destruction of any Product components, if a Productbecomes defective; (vi)place any Product onto a"
	"server other than the designated server or otherwise make suchProduct accessible to other users or"
	"the public; (vii)use aProduct to provide third parties with managed services or any other services"
	"whether or not in return for remuneration of any kind; (viii)disclose the results of any testing or"
	"benchmarking of a Product to any third party; (ix)remove or alter any trademarks or other proprietary"
	"right notices displayed on or in a Product, ; (x)circumvent, disable or otherwise interfere with security -"
	"related features of a Product or features that enforce use limitations; (xi) export, make available or use"
	"a Product in any manner prohibited by applicable laws; and /or (xii)store or transmit any malicious"
	"code(i.e., software viruses, Trojan horses, worms, robots, malware, spyware or other computer"
	"instructions, devices, or techniques that erase data or programming, infect, disrupt, damage, disable,"
	"or shut down a computer system or any component of such computer system) or other unlawful material"
	"in connection with a Product."
	"\n"
	"For the avoidance of doubt, use of any third - party applications provided by XiaoBuild with the"
	"Software Product and /or the Cloud Services is expressly limited to use in conjunction with the Software"
	"Product and /or the Cloud Services, and may not be used independently, unless agreed otherwise"
	"between Licensee and the provider of the applicable third party application."
	"\n"
	"In addition to the restrictions above, the use of any Product is subject to usage limits as defined in an"
	"applicable Quote or the Partner Order Form(as the case may be)."
	"\n"
	"Licensee will prevent unauthorized access to or use of the Products and notify XiaoBuild promptly of"
	"any such unauthorized access or use."
	"\n"
	"3. DOCUMENTATION."
	"\n"
	"In purchasing a Subscription License, XiaoBuild may make available to Licensee user’s guides and"
	"technical manuals(\"Documentation\").The Documentation may be used by Licensee solely in"
	"connection with Licensee’s use of the Software Product, Cloud Services or any Feature(as the case"
	"	may be) during the Subscription Term.Licensee may print or copy the Documentation as needed for"
	"its own internal business purposes provided that all copyright notices are included therein.The"
	"Documentation shall be considered XiaoBuild's Confidential Information (as defined below)."
	"\n"
	"4. CLOUD SERVICES"
	"\n"
	"The Cloud Services shall be provided on Licensee's cloud account operated by a third party cloud "
	"partner who's cloud interacts with XiaoBuild's technology(\"Cloud Partner(s)\") and is subject to the"
	"terms of use or other agreement agreed between Licensee and the relevant Cloud Partner(\"Cloud"
	"	Partner Terms”).Licensee acknowledges and agrees that the Cloud Partner Terms are concluded"
	"between the Cloud Partner and Licensee only, and not with XiaoBuild.All payments related to"
	"Licensee's use of Cloud shall be paid directly to Licensee's Cloud Partner."
	"\n"
	"The Cloud Services may be used through an XiaoBuild account(\"Account\"), which may be accessed"
	"only by Licensee’s employees who are explicitly authorized by Licensee to use the Cloud Services,"
	"(each, a \"Permitted User\").Licensee will ensure that the Permitted Users comply with the terms of this"
	"Agreement; and will be fully responsible for any breach of this Agreement by a Permitted User."
	"Licensee will ensure that the Permitted Users keep the Account login details secure at all times, and"
	"shall be fully responsible for all activities performed by Permitted Users in relation to the Account."
	"\n"
	"Licensee hereby grants XiaoBuild permission to : (i)create a virtual private cloud(\"Virtual Private "
	"	Cloud\") within Licensee's Microsoft Azure Resource Group cloud, AWS Virtual Private Cloud or any "
	"	other cloud account operated by a Cloud Partner that XiaoBuild's technology interacts with (as "
	"	applicable) (each a \"Cloud\") that is linked to Licensee's Account; and (ii) manage such Virtual Private "
	"Cloud on Licensee's behalf. Licensee agrees that Licensee shall not make any modifications to the "
	"Cloud and XiaoBuild has no responsibility or liability for any such modifications made by Licensee or"
	"a Permitted User.In order to use the Cloud Services, Licensee must obtain a valid and stable"
	"communication with the Cloud Services mechanism.In case of lack of internet connectivity for a period"
	"exceeding those number of days specified in the Documentation, XiaoBuild may prevent Licensee's "
	"access to the Software Product and Cloud Services, including by way of locking the use remotely."
	"\n"
	"Licensee acknowledges and agrees that during the deployment and use of the Cloud Services,"
	"Licensee's Cloud Partner may identify the installation of the Cloud Services and have access to certain "
	"data related thereto, as may be further detailed in the Cloud Partner Terms and the Cloud Partner's "
	"privacy policy.XiaoBuild does not control and assumes no liability for the Cloud Partner's use of data "
	"or privacy practices and encourages Licensee to read the Cloud Partner Terms and the Cloud"
	"Partner's privacy policy. To clarify, when Licensee uses a Cloud Partner, XiaoBuild will deploy such "
	"Cloud Partner resources.Then, the selected Cloud Partner can identify XiaoBuild's installation and "
	"can correlate these resources to support the Cloud.Such Cloud Partner may collect this information to"
	"provide its products and to operate its business.The data is collected and governed by the Cloud"
	"Partner’s privacy policies, located at the Cloud Partner’s website."
	"\n"
	"Licensee hereby agrees to and hereby releases and forever discharges XiaoBuild and its respective"
	"assigns from all claims, demands or damages arising out of or in any way related to any fee or amount,"
	"including, without limitation, taxes, billing, payments, processing, invoices, charged or overcharged by"
	"the Cloud Partner and any other issue or dispute relating thereto and /or related to the Cloud."
	"\n"
	"The parties agree that to the maximum extent permitted by law : (a)XiaoBuild is merely utilizing the"
	"Licensee's Cloud and is not providing the Cloud itself; (b) XiaoBuild bears no responsibility or liability "
	"of any kind in relation to the Licensee's Cloud, including, without limitation, in relation to any disputes "
	"between Licensee and the Cloud Partner and /or such third parties."
	"\n"
	"Licensee hereby agrees and acknowledges that the Cloud Partner(and not XiaoBuild) shall provide"
	"Licensee with support and maintenance services related to the Licensee's Cloud, and shall be "
	"responsible for the availability, and all other aspects, of the Licensee's Cloud."
	"\n"
	"5. INTELLECTUAL PROPERTY RIGHTS."
	"\n"
	"The Software Product, Cloud Services and any Feature are not for sale and are XiaoBuild’s sole"
	"property.All right, title, and interest, including any intellectual property rights evidenced by or embodied"
	"in, attached, connected, and /or related to the Software Product and Cloud Services and any and all"
	"Features, improvements and derivative works thereof(regardless of whether such derivative works"
	"	were made and /or developed pursuant to the request and /or specifications of Licensee, and"
	"	irrespective of any support and /or assistance XiaoBuild may, will or had received from Licensee, or"
	"	any third party on its behalf, with respect thereto), as well as any updates thereto, are and shall remain"
	"owned solely by XiaoBuild or its licensors.This Agreement does not convey to Licensee any interest"
	"in or to the Software Product, Cloud Services and any Feature other than a limited right to use them in"
	"accordance with the terms of this Agreement.Nothing herein constitutes a waiver of XiaoBuild’s"
	"intellectual property rights under any law, or be in any way construed or interpreted as such."
	"\n"
	"If XiaoBuild receives any feedback(e.g., questions, comments, suggestions or the like, whether"
	"	orally or in writing) (collectively, \"Feedback\"), all rights, including intellectual property rights in such"
	"Feedback shall belong exclusively to XiaoBuild and that such shall be considered XiaoBuild’s"
	"Confidential Information and Licensee hereby irrevocably and unconditionally transfers and assigns to"
	"XiaoBuild all intellectual property rights it has in such Feedback and waives any and all moral rights"
	"that Licensee may have in respect thereto.It is further understood that use of Feedback, if any, may be"
	"made by XiaoBuild at its sole discretion, and that XiaoBuild in no way shall be obliged to make use"
	"of any kind of the Feedback or part thereof."
	"\n"
	"Portions of the Software distributed to Licensee as part of the Software Product, Cloud Services and /or"
	"Feature may include third party open source software(\"Open Source Software\") that is subject to third"
	"party terms and conditions(\"Third Party Terms\").A list of the Open Source Software and related Third"
	"Party Terms is available within the XiaoBuild open source list available here, as may be updated"
	"from time to time by XiaoBuild at its sole discretion.If there is a conflict between any Third Party"
	"Terms and the terms of this Agreement, then the Third Party Terms shall prevail but solely in connection"
	"with the related to such respective Open Source Software.Without derogating from the generality of"
	"the foregoing, it is clarified that any Open Source Software is provided on an \"AS IS\" basis, without"
	"warranty of any kind, whether express, implied or statutory.Notwithstanding anything in this Agreement"
	"to the contrary, XiaoBuild is not liable for any losses or damages which may occur resulting from the"
	"use of any Open Source Software."
	"\n"
	"Any generic and anonymous information, which is derived from the use of the Software Product, Cloud"
	"Services or Feature(i.e., metadata, aggregated and /or analytics information) which is not personally"
	"identifiable information is XiaoBuild’s exclusive property and may be used for any purpose including,"
	"but not limited to for development and /or for statistical purposes."
	"\n"
	"6. SUPPORT."
	"\n"
	"During the Subscription Term, subject to Licensee’s compliance with its obligations under this"
	"Agreement(including, without limitation, payments obligations), XiaoBuild will provide Licensee the"
	"maintenance and support services applicable to the package purchased by Licensee, as described in"
	"the XiaoBuild Service Agreement(\"SLA\"), available at : https://www.XiaoBuild.com/sla, as "
	"amended by XiaoBuild from time to time ar its sole discretion."
	"\n"
	"7. PAYMENT."
	"\n"
	"General.This section 7 is applicable solely to purchases made directly from XiaoBuild.If Licensee"
	"has purchased any of the licenses granted under Section 1 via a Partner or via the Marketplace, the"
	"license granted hereunder and the related services are subject to the full payment of the applicable"
	"fees as set forth in the Partner Order Form between Licensee and the respective Partner or the"
	"Marketplace terms and conditions(as applicable).For Cloud Services purchased via an online"
	"Marketplace, all payments and license fees shall be made to, and processed by, such Marketplace"
	"operator and may be subject to additional terms and conditions applicable to such Marketplace."
	"\n"
	"7.1 Subscription Fees.Licensee’s use of the Software Product and Cloud Services is subject to up -"
	"front payment in full of the subscription fees set forth in the Quote(\"Subscription Fee\").Licensee"
	"acknowledges that the Subscription Fee during any Renewal Subscription Term will, unless set forth in"
	"the Quote, be determined by XiaoBuild’s then - current subscription fees, as amended from time to"
	"time at XiaoBuild’s sole discretion."
	"\n"
	"7.2 Payment Terms.Unless specified otherwise in the Quote, payment shall be due within thirty(30)"
	"days of receipt of XiaoBuild’s invoice which shall be issued at the beginning of each year during the"
	"Subscription Term.Any payment or part of a payment that is not paid by Licensee to XiaoBuild when"
	"due shall bear interest at the rate of 1.5 % per month or any part thereof(but shall not exceed the"
	"maximum rate allowed by applicable law) and shall constitute sufficient cause for XiaoBuild to"
	"immediately suspend its performance hereunder and terminate this Agreement and the Subscription"
	"License.All fees are stated, and shall be paid, in US Dollars, by wire transfer to an account designated"
	"by XiaoBuild, are non - refundable and are exclusive of all taxes, levies, or duties, which are"
	"Licensee’s responsibility."
	"\n"
	"7.3 Taxes.The Subscription Fee shall not be subject to any set - off or deduction and are exclusive of"
	"any applicable taxes, duties and similar governmental charges, and, except with respect to income"
	"taxes of XiaoBuild.Licensee is responsible for payment of all such amounts, including sales tax,"
	"value added tax(VAT), withholding taxes, export, import and other duties imposed by any"
	"governmental agency in connection with this Agreement.Licensee agrees to hold harmless"
	"XiaoBuild from all claims and liability arising from Licensee’s failure to report or pay such taxes,"
	"duties or other governmental charges.If XiaoBuild will be required to pay any such taxes, then such"
	"taxes shall be billed to and paid by Licensee.If any taxes are required to be withheld, Licensee shall"
	"pay an amount to XiaoBuild so that the net amount payable to XiaoBuild after withholding of taxes"
	"shall equal the amount that would have been otherwise payable under this Agreement.Licensee"
	"agrees to hold harmless XiaoBuild from all claims and liabilities arising from Licensee’s failure to"
	"report or pay any taxes."
	"\n"
	"8. WARRANTIES."
	"\n"
	"By using, downloading or otherwise installing any XiaoBuild Product, Licensee represents and"
	"warrants that it is duly organized, validly existing and in good standing under the laws of its jurisdiction"
	"of incorporation or organization; and that the execution and performance of this Agreement will not"
	"conflict with other agreements to which it is bound or violate applicable law."
	"\n"
	"TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE PRODUCT, CLOUD"											
	"SERVICES AND ALL RELATED FEATURES AND SERVICES ARE PROVIDED ON AN \"AS IS\""
	"BASIS.XiaoBuild HEREBY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED,"
	"INCLUDING BUT NOT LIMITED, IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS"
	"FOR A PARTICULAR PURPOSE, NON - INFRINGEMENT OR QUALITY OF SERVICE."
	"XiaoBuild DOES NOT WARRANT THAT THE SOFTWARE PRODUCT AND CLOUD"
	"SERVICES WILL BE UNINTERRUPTED, ERROR FREE, OR THAT DEFECTS WILL BE"
	"CORRECTED.XiaoBuild DOES NOT CONTROL, AND IS NOT RESPONSIBLE FOR, THE"
	"LICENSEE'S CLOUD, THE CLOUD PARTNER(S), THE MARKETPLACE OR ANY THIRD PARTY\'S "
	"ACTS OR OMISSIONS, AND SHALL HAVE NO LIABILITY FOR ANY FAILURE, UNAVAILABILITY OR"
	"DEGRADATION OF THE LICENSEE'S CLOUD, CLOUD PARTNER, THE MARKETPLACE OR ANY "
	"THIRD PARTY BEYOND XiaoBuild\'S REASONABLE CONTROL.THE INDEPENDENT"
	"MODIFICATION OF THE CLOUD PARTNER TERMS AND / OR LICENSEE'S CLOUD COULD "
	"ADVERSELY IMPACT THE FUNCTIONALITY OR QUALITY OF CLOUD SERVICES, AND"
	"XiaoBuild SHALL NOT HAVE ANY LIABILITY OR RESPONSIBILITY(INCLUDING TO PROVIDE"
	"	ANY REFUNDS) IF SUCH ADVERSE IMPACT OCCURS.XiaoBuild SHALL NOT BE"
	"RESPONSIBLE FOR ANY UNAVAILBILTY OF THE MARKETPLACE AND / OR ANY DISPUTES"
	"RELATED TO PAYMENT PROCESSING, INVOICING AND BILLING BY THE"
	"PARTNER / MARKETPLACE, OR LICENSEE'S PAYMENT OBLIGATIONS TO THE PARTNER "
	"AND.ORMARKETPLACE."
	"\n"
	"THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS AGREEMENT."
	"IN THE EVENT A COMPENTENT COURT RULING STATES THAT SOME OR ALL OF THE ABOVE"
	"EXCLUSIONS OF IMPLIED WARRANTY ARE NOT APPLICABLE IN A CREATIN HURISDICTION,"
	"THIS DISCLAIMER WILL BE INTERPRETED TO APPLY EQUIVALENT LEGAL RIGHTS TO"
	"MAINTAIN SUCH EXCLUSIONS IN THAT CERTAIN JURISDICTION."
	"\n"
	"9. CONFIDENTIALITY."
	"\n"
	"Each party may have access to certain non - public information of the other party, in any form or media,"
	"including without limitation trade secrets and other information related to the products, software,"
	"technology, data, know - how, or business of the other party, and any other information that a reasonable"
	"person should have reason to believe is confidential, or competitively sensitive(the \"Confidential"
	"	Information\").Each party shall take measures, at least as protective as those taken to protect its own"
	"confidential information, but in no event less than reasonable care, to protect the other party’s"
	"Confidential Information from disclosure to a third party.The receiving party’s obligations under this"
	"Section 9, with respect to any Confidential Information of the disclosing party, shall not apply to and /or"
	"shall terminate if such information : (a)was already lawfully known to the receiving party at the time of"
	"disclosure by the disclosing party; (b)was disclosed to the receiving party by a third party who had the"
	"right to make such disclosure without any confidentiality restrictions; (c)is, or through no fault of the"
	"receiving party has become, generally available to the public; or (d)was independently developed by"
	"the receiving party without access to, or use of, the disclosing party’s Confidential Information.Neither"
	"party shall use or disclose the Confidential Information of the other party except for performance of its"
	"obligations under this Agreement(“Permitted Use”).The receiving party shall only permit access to the"
	"disclosing party’s Confidential Information to its respective employees, consultants, affiliates, agents"
	"and subcontractors having a need to know such information in connection with the Permitted Use, who"
	"either(i) have signed a non - disclosure agreement with the receiving party containing terms at least as"
	"restrictive as those contained herein or (ii)are otherwise bound by a duty of confidentiality to the"
	"receiving party at least as restrictive as the terms set forth herein.The receiving party will be allowed to"
	"disclose Confidential Information to the extent that such disclosure is required by law or by the order or"
	"a court of similar judicial or administrative body, provided that it notifies the disclosing party of such"
	"required disclosure to enable the disclosing party to seek a protective order or otherwise prevent or"
	"restrict such disclosure.All right, title and interest in and to Confidential Information are and shall"
	"remain the sole and exclusive property of the disclosing Party."
	"\n"
	"10. LIMITATION OF LIABILITY."
	"\n"
	"LICENSEE ASSUMES THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE"
	"SOFTWARE PRODUCT, CLOUD SERVICES AND ANY FEATURE.XiaoBuild ASSUMES NO"
	"LIABILITY FOR THE COST OF ANY SERVICE OR REPAIR IF THE SOFTWARE PRODUCT, CLOUD"
	"SERVICES OR ANY FEATURE ARE DEFECTIVE.XiaoBuild SHALL NOT BE LIABLE FOR"
	"ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES,"
	"INCLUDING, WITHOUT LIMITATION ANY LOSS OF REVENUE, REPUTATION, OR PROFITS, DATA,"
	"OR DATA USE, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, HOWEVER"
	"CAUSED, AND ON ANY THEORY OF LIABILITY, WHETHER FOR BREACH OF CONTRACT, TORT"
	"(INCLUDING NEGLIGENCE AND STRICT LIABILITY) OR OTHERWISE, WHETHER OR NOT"
	"XiaoBuild HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES."
	"\n"																												
	"XiaoBuild WILL HAVE NO INDEMNITY, SUPPORT, OR OTHER OBLIGATIONS OR LIABILITIES"
	"WITH RESPECT TO THE SOFTWARE PRODUCT AND / OR CLOUD SERVICES AND / OR FEATURE"
	"PROVIDED UNDER THE EVALUATION LICENSE AND / OR FREE LICENSE, AND SHALL NOT BE"
	"LIABLE FOR ANY DAMAGES WHATSOEVER(INCLUDING, WITHOUT LIMITATION, DIRECT,"
	"	INDIRECT, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE OR INCIDENTAL DAMAGES,"
	"	OR DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF"
	"	BUSINESS INFORMATION, LOSS OF DATA OR OTHER PECUNIARY LOSS) ARISING OUT OF THE"
	"USE OF OR INABILITY TO USE THE SOFTWARE PRODUCT AND / OR CLOUD SERVICES, EVEN"
	"IF XiaoBuild HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES."
	"\n"
	"EXCEPT FOR XiaoBuild’S INDEMNIFICATION OBLIGATION UNDER SECTION 11;"
	"XiaoBuild’S MAXIMUM LIABILITY FOR ANY DAMAGES ARISING OUT OF OR RELATED TO"
	"THIS AGREEMENT, WHETHER IN CONTRACT OR TORT, OR OTHERWISE, SHALL IN NO EVENT"
	"EXCEED, IN THE AGGREGATE, THE TOTAL AMOUNTS ACTUALLY PAID TO XiaoBuild"
	"UNDER THIS AGREEMENT IN THE SIX(6) MONTH PERIOD IMMEDIATELY PRECEDING THE"
	"EVENT GIVING RISE TO SUCH CLAIM.THIS LIMITATION OF LIABILITY IS CUMULATIVE AND NOT"
	"PER INCIDENT.NOTWITHSTANDING, THE LIMITATIONS IN THIS SECTION 10 DO NOT"
	"DEROGATE FROM ANY RIGHT XiaoBuild MAY HAVE WITH RESPECT TO PAYMENTS DUE"
	"TO XiaoBuild UNDER THIS AGREEMENT."
	"\n"
	"THIS LIMITATION OF LIABILITY SHALL NOT APPLY TO LIABILITY FOR DEATH OR PERSONAL"
	"INJURY TO THE EXTENT APPLICABLE LAW PROHIBITS SUCH LIMITATION.FURTHERMORE,"
	"SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR"
	"CONSEQUENTIAL DAMAGES, ANF APPLICATION THEREOF SHALL BE MADE IN"
	"ACCORDANCE WITH THE APPLICABLE LAW."
	"\n"
	"11. INDEMNIFICATION."
	"\n"
	"XiaoBuild agrees to defend, at its expense, any third party action or suit brought against the"
	"Licensee alleging that the Software Product and /or Cloud Services, when used as permitted under this"
	"Agreement, infringes copyrights, patent or trademarks of a third party(\"IP Infringement Claim\"); and"
	"XiaoBuild will pay any damages and liabilities awarded in a final judgment against the Licensee that"
	"are attributable to any such claim, provided that(i) the Licensee promptly notifies XiaoBuild in writing"
	"of such claim; and (ii)Licensee grants XiaoBuild the sole authority to handle the defense or"
	"settlement of any such claim and provides XiaoBuild with all reasonable information and assistance,"
	"at XiaoBuild’s expense.XiaoBuild will not be bound by any settlement that the Licensee enters into"
	"without XiaoBuild’s prior written consent."
	"\n"
	"If the Software Product and /or Cloud Services become, or in XiaoBuild’s opinion are likely to"
	"become, the subject of an IP Infringement Claim, then XiaoBuild may, at its sole discretion : (a)"
	"procure for Licensee the right to continue using the Software Product and /or Cloud Services(as the"
	"case may be); (b)replace or modify the Software Product and /or Cloud Services(as the case may be)"
	"to avoid the IP Infringement Claim; or (c) if options(a) and (b)cannot be accomplished despite"					
	"XiaoBuild’s reasonable efforts, then XiaoBuild may terminate this Agreement and in such event"
	"accept return of the affected Software Product and /or Cloud Services(as the case may be) and"
	"provide a refund for any amount pre - paid by Licensee for such returned Software Product and /or Cloud"
	"Services(as the case may be) for the remaining unused period of the Subscription Term."
	"\n"
	"Notwithstanding the foregoing, XiaoBuild shall have no responsibility for IP Infringement Claims"
	"resulting from or based on : (i)modifications to the Software Product and /or Cloud Services made by a"
	"party other than XiaoBuild or its designee; (ii)the Licensee’s failure to implement software updates"
	"provided by XiaoBuild specifically to avoid infringement; or (iii)combination or use of the Software"
	"Product and /or Cloud Services with equipment, devices or software not supplied by XiaoBuild or not"
	"in accordance with its documentation."
	"\n"
	"This Section 11 states XiaoBuild’s entire liability, and Licensee’s exclusive remedy, for claims or"
	"alleged or actual infringement."
	"\n"
	"For the avoidance of doubt, XiaoBuild’s indemnification obligation under this Section 11 shall not"
	"apply to Licensee for Evaluation License and /or Free License."
	"\n"
	"12. TERM AND TERMINATION."
	"\n"
	"Commencement Date : This Agreement shall enter into force and effect on the earlier of : (i)the date"
	"that Licensee commences access to, or uses of the Software Product and /or Cloud Services; or (ii)"
	"the date that XiaoBuild receives payment of any applicable Subscription Fees.Unless terminated"
	"earlier in accordance with the terms of this Section 12, this Agreement shall continue in full force and"
	"effect until expiration of the initial license period specified in the Quote or the Partner Order Form(as"
	"	the case may be) (the \"Initial Subscription Term\")."
	"\n"
	"Renewal: If the Subscription License is purchased directly from XiaoBuild, unless otherwise is stated"
	"in the applicable quote, this Agreement shall automatically renew for successive license of one(1) year"
	"periods(each a “Renewal Subscription Term“, and together with the Initial Subscription Term, the"
	"	\"Subscription Term\"), unless XiaoBuild or Licensee provides a written notice to the other party within"
	"sixty(60) days prior to the expiration of the then current term of its intention not to renew this"
	"Agreement.If the Subscription License is purchased from the Marketplace or a Partner, the"
	"Subscription License shall renew in accordance with the terms specified within the Partner Order"
	"Form."
	"\n"
	"Licensee Third Party Cloud : XiaoBuild shall automatically and immediately cease to provide Cloud"
	"Services if, during a Subscription Term, Licensee terminates its Cloud and does not purchase an"
	"alternative Cloud.If Licensee continues to use the Software Product and /or Could Services past any"
	"license period renewal date, Licensee shall be deemed to have renewed this Agreement for the"
	"corresponding Renewal Subscription Term."
	"\n"
	"Evaluation and Free License : Notwithstanding the above, the duration of the Evaluation License and"
	"the Free License shall be in accordance with the provisions of Section 2 and the applicable Quote"
	"provided that XiaoBuild may at any time terminate the Evaluation License and the Free License"
	"immediately upon notice to Licensee(email acceptable)."
	"\n"
	"Termination For Cause : Either Party may terminate this Agreement with immediate effect, and"
	"XiaoBuild may block the use of the Software Product and Cloud Services, if : (a)the other party"
	"materially breaches this Agreement and such breach remains uncured fifteen(15) days after having"
	"received written notice thereof; or (b)the other party is unable to pay its debts or becomes insolvent, is"
	"the subject of an order made or a resolution passed for its administration, winding - up or dissolution"
	"(otherwise than for the purpose of a solvent amalgamation or reconstruction), or is the subject of any"
	"events or circumstances analogous to the foregoing; or (c)Licensee has received the Software"
	"Product and /or Cloud Service and /or Feature pursuant to an Evaluation or Free License."
	"Notwithstanding the foregoing, if Licensee has purchased a subscription to use the Software Product"
	"and /or Cloud Service via the Marketplace or a Partner, (a)the Marketplace operator and/or Partner(as"
	"	applicable) may terminate and /or suspend Licensee's use of the Software Product and/or Cloud "
	"Service in accordance with the Partner Order Form; and (b)XiaoBuild may terminate this Agreement"
	"with immediate effect if Licensee fails to pay the applicable payments and license fees to Marketplace"
	"operator and/or Partner(as applicable)."
	"\n"
	"Effects of Termiantion : Upon termination or expiration of this Agreement : (a)Licensee will : (i)"
	"immediately cease use of the Software Product and Cloud Services; (ii) return the Software and all"
	"copies thereof, as well as the Documentation to XiaoBuild; (iii)erase or otherwise destroy all copies"
	"of the Software in its possession, which is fixed or resident in the memory or hard disks of its"
	"computers and certify in writing to XiaoBuild that all copies(including partial copies) of the Software"
	"Product, Cloud Services and related Documentation have been returned to XiaoBuild or otherwise"
	"erased, destroyed and deleted from any computer libraries or storage devices; and (v) return to"
	"XiaoBuild any and all Confidential Information then in its possession; (b)XiaoBuild will delete"
	"Licensee's Virtual Private Cloud, including its entire content. Notwithstanding anything to the contrary, it "
	"is Licensee's sole responsibility to check and verify that the entire content of Licensee's Virtual Private"
	"Cloud(has been deleted and to remove the permission that Licensee provided to XiaoBuild to"
	"	manage its Virtual Private Cloud.XiaoBuild is not responsible for any costs that may arise due to"
	"	Licensee's failure to delete and remove content from its Virtual Private Cloud. Termination of this "
	"	Agreement shall be without prejudice to the rights and remedies of either Party which have accrued up"
	"	to the date of termination.Sections 5 (Intellectual Property Rights), 9 (Confidentiality), 10 (Limited"
	"		Warranties), 11 (Limitation of Liability), 15 (Usage Audit) and 17 (Miscellaneous)shall survive the"
	"	termination of this Agreement."
	"\n"
	"	14. USE OF DATA."
	"\n"
	"	14.1 Unless otherwise stated in a separate document(e.g.data processing agreement or privacy"
	"		policy), during the process of registration to use the Subscription License, XiaoBuild may request"
	"	Licensee to provide its contact information, such as : full name, organization name, phone number, valid"
	"	email address and similar data, and XiaoBuild may use this information(i) to provide, maintain and"
	"	improve the Software Product Cloud Services and other XiaoBuild’s services, perform this"
	"	Agreement, and for related purposes, and (ii)to contact Licensee to provide Licensee with important"
	"	information, software updates, required notices, marketing promotions and related purposes."
	"	XiaoBuild also reserves the right to use Licensee name and logo to present Licensee as a customer"
	"	in XiaoBuild’s website and other social media advertising or marketing promotions XiaoBuild"
	"	makes from time to time.Licensee agrees to serve as a reference customer of XiaoBuild and will"
	"	cooperate with XiaoBuild’s reasonable marketing and referencing requests."								
	"\n"
	"	14.2 If Licensee needs to execute a Data Processing Agreement(\"DPA\"), Licensee is required to"
	"	obtain the XiaoBuild’s DPA and return a signed copy of the DPA to XiaoBuild.In the event Licensee"
	"	fails to execute such DPA when required to do so by law or regulation, or to comply with any applicable"
	"	data protection or privacy law or regulation and /or any provision of the DPA, Licensee shall be solely"
	"	and fully responsible and liable for any such breach, violation, infringement and /or processing of"
	"	personal data without a DPA."
	"\n"
	"	15. USAGE AUDIT."
	"\n"
	"	XiaoBuild may request that Licensee furnish it with a report with respect to the use by Licensee of the"
	"	Software Product and /or Cloud Services in order to verify Licensee’s usage of the Software Product"
	"	and /or Cloud Services in accordance with the terms of this Agreement.Without derogating from the"
	"	foregoing, XiaoBuild shall be entitled to audit Licensee’s usage of the Software Product and /or"
	"	Cloud Services at Licensee’s facilities in order to verify proper usage in accordance with the terms"
	"	herein.Such audits shall be scheduled a reasonable time in advance during Licensee’s normal"
	"	business hours.If the audit uncovers any Licensee wrongful act, then, on top of any other applicable"
	"	remedy available to XiaoBuild at law or in equity, the cost of such auditing shall be borne by"
	"	Licensee.By requesting an audit, XiaoBuild does not waive its rights to enforce this Agreement or to"
	"	protect our intellectual property by any other means permitted by law."
	"\n"
	"	16. EXPORT CONTROL."
	"\n"
	"	Licensee acknowledges that the laws and regulations of the United States, as well as other foreign"
	"	authorities, may restrict the export and re - export of certain commodities and technical data, including"
	"	the Software Product Cloud Services and Documentation.Licensee agrees not to export or re - export"
	"	the Software Product, Cloud Services and Documentation in any form without the appropriate United"
	"	States and foreign governmental licenses."
	"\n"
	"	17. MISCELLANEOUS."
	"\n"
	"	This Agreement represents the complete agreement concerning the subject matter hereof.XiaoBuild"
	"	reserves the right to modify this Agreement at any time by sending you a notification of such change(in"
	"		case of a material change) and /or publishing the revised Agreement on XiaoBuild\'s website.Such"
	"	change will be effective ten(10) days following the foregoing notification thereof.The failure of either"
	"	party to enforce any rights granted hereunder or to take action against the other party in the event of"
	"	any breach hereunder shall not be deemed a waiver by that Party as to subsequent enforcement of"
	"	rights or subsequent actions in the event of future breaches.If any provision of this Agreement is held"
	"	to be unenforceable, such provision shall be reformed only to the extent necessary to make it"
	"	enforceable.Any use of the Software Product and Cloud Services by an agency, department, or other"
	"	entity of the United States government shall be governed solely by the terms of this Agreement.This"
	"	Agreement, and any rights and licenses granted hereunder, may not be transferred or assigned by"
	"	Licensee without XiaoBuild's written consent, but may be assigned by XiaoBuild without restriction "
	"	or notification.Any assignment in breach of this Agreement shall be null and void.This Agreement shall"
	"	be governed by and construed under the laws of the State of Israel.The competent courts of Tel - Aviv,"
	"	Israel shall have the exclusive jurisdiction with respect to any dispute and action arising under or in"
	"	relation to this Agreement.This Agreement does not, and shall not be construed to create any"
	"	relationship, partnership, joint venture, employer - employee, agency, or franchisor - franchisee"
	"	relationship between the parties.XiaoBuild will not be liable for any delay or failure to comply with its"
	"	obligations resulting from circumstances or causes beyond the reasonable control of the XiaoBuild.");

#undef LOCTEXT_NAMESPACE